/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bd_departamentos;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.management.Query;

/**
 *
 * @author prg
 */
public class Panel extends javax.swing.JPanel {

    MySQL myDb = new MySQL();
    int indice = -1;
    Connection c;
    int fila = 0;
    int tamanio;

    public Panel(MySQL myDb, Connection c) {

        this.myDb = myDb;

        this.c = c;

        initComponents();

        try {
            llenarComponentes();

        } catch (SQLException ex) {

        }

        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jldep = new javax.swing.JLabel();
        jlid = new javax.swing.JLabel();
        jlciudad = new javax.swing.JLabel();
        jlobjanual = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaSalida = new javax.swing.JTextArea();
        jtfid = new javax.swing.JTextField();
        jtfciudad = new javax.swing.JTextField();
        jtfobjanual = new javax.swing.JTextField();
        jbtinsertar = new javax.swing.JButton();
        jbtborrar = new javax.swing.JButton();
        jbtactualizar = new javax.swing.JButton();
        jbtver = new javax.swing.JButton();
        jBtAnterior = new javax.swing.JButton();
        jBtSiguiente = new javax.swing.JButton();

        jLabel2.setText("jLabel2");

        jLabel3.setText("jLabel3");

        jldep.setText("Departamentos");

        jlid.setText("idDep");

        jlciudad.setText("Ciudad");

        jlobjanual.setText("objAnual");

        jtaSalida.setColumns(20);
        jtaSalida.setRows(5);
        jScrollPane1.setViewportView(jtaSalida);

        jbtinsertar.setText("Insertar");
        jbtinsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtinsertarActionPerformed(evt);
            }
        });

        jbtborrar.setText("Borrar");
        jbtborrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtborrarActionPerformed(evt);
            }
        });

        jbtactualizar.setText("Actualizar");
        jbtactualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtactualizarActionPerformed(evt);
            }
        });

        jbtver.setText("Ver");
        jbtver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtverActionPerformed(evt);
            }
        });

        jBtAnterior.setText("<");
        jBtAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtAnteriorActionPerformed(evt);
            }
        });

        jBtSiguiente.setText(">");
        jBtSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtSiguienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jldep))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlciudad)
                            .addComponent(jlid)
                            .addComponent(jlobjanual))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtfid, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                            .addComponent(jtfciudad)
                            .addComponent(jtfobjanual)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jBtAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jBtSiguiente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(141, 141, 141)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jbtver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtborrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtinsertar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtactualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(65, 65, 65))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jldep)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlid)
                    .addComponent(jtfid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtinsertar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfciudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlciudad)
                    .addComponent(jbtborrar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlobjanual)
                    .addComponent(jtfobjanual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtactualizar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtver)
                    .addComponent(jBtAnterior)
                    .addComponent(jBtSiguiente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbtinsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtinsertarActionPerformed

        String s = "";

        String id = jtfid.getText();
        String ciudad = jtfciudad.getText();
        String objA = jtfobjanual.getText();

        s = myDb.consulta("insert into departamentos values (" + id + ",\"" + ciudad + "\"," + objA + ")");

        this.jtaSalida.setText(s);

    }//GEN-LAST:event_jbtinsertarActionPerformed

    private void jbtborrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtborrarActionPerformed
        String s = "";

        String id = jtfid.getText();

        s = myDb.consulta("delete from departamentos where idDep=(" + id + ")");

        this.jtaSalida.setText(s);
    }//GEN-LAST:event_jbtborrarActionPerformed

    private void jbtactualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtactualizarActionPerformed

        String s = "";

        String id = jtfid.getText();
        String ciudad = jtfciudad.getText();
        String objA = jtfobjanual.getText();

        s = myDb.consulta("update departamentos set ciudad = '" + ciudad + "' where idDep = " + id);
        s += " " + myDb.consulta("update departamentos set objetivoAnual = " + objA + " where idDep like " + id);

        this.jtaSalida.setText(s);

    }//GEN-LAST:event_jbtactualizarActionPerformed

    private void jbtverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtverActionPerformed


    }//GEN-LAST:event_jbtverActionPerformed

    private void jBtAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtAnteriorActionPerformed
      
        jBtSiguiente.setEnabled(true);

        if (fila > 0 ) {

            fila--;
            
            try {
                llenarComponentes();
                
            } catch (SQLException ex) {
                
            }

        }else{
            jBtAnterior.setEnabled(false);
        }

    }//GEN-LAST:event_jBtAnteriorActionPerformed

    private void jBtSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtSiguienteActionPerformed

        jBtAnterior.setEnabled(true);
        
        if (fila != tamanio) {

            fila++;
            
            try {
                llenarComponentes();
                
            } catch (SQLException ex) {
                
            }

        }else{
            jBtSiguiente.setEnabled(false);
        }

    }//GEN-LAST:event_jBtSiguienteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtAnterior;
    private javax.swing.JButton jBtSiguiente;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtactualizar;
    private javax.swing.JButton jbtborrar;
    private javax.swing.JButton jbtinsertar;
    private javax.swing.JButton jbtver;
    private javax.swing.JLabel jlciudad;
    private javax.swing.JLabel jldep;
    private javax.swing.JLabel jlid;
    private javax.swing.JLabel jlobjanual;
    private javax.swing.JTextArea jtaSalida;
    private javax.swing.JTextField jtfciudad;
    private javax.swing.JTextField jtfid;
    private javax.swing.JTextField jtfobjanual;
    // End of variables declaration//GEN-END:variables

    private void llenarComponentes() throws SQLException {

        try {
            ResultSet rs;
            Statement st = c.createStatement();
            String query = "departamentos";

            rs = st.executeQuery(query);
            
            System.out.println(rs.toString());

            String[][] s = (String[][]) myDb.getValues(query);
            

            this.jtfid.setText(s[fila][1]);
            this.jtfciudad.setText(s[fila][2]);
            this.jtfobjanual.setText(s[fila][3]);

        } catch (Exception e) {

            this.jtaSalida.setText(e.getMessage());
        }

    }

}
